CREATE TABLE EMPLOYEE
(
	EMPLOYEE_OID	number(10) NOT NULL,
	EMPLOYEE_NAME	varchar2(50) NOT NULL,
	-- audit fields --
	VERSION			number(10),
	CREATE_DATE		timestamp(6) DEFAULT SYSDATE,
	CREATE_USER		number(10) DEFAULT 1,
	UPDATE_DATE		timestamp(6) DEFAULT SYSDATE,
	UPDATE_USER		number(10) DEFAULT 1,
	------------------
	CONSTRAINT	PK_EMPLOYEE	PRIMARY KEY	(EMPLOYEE_OID)
);