spring:
  datasource:
    ## in memory mode
    #url: jdbc:h2:mem:testdb;Mode=Oracle;DB_CLOSE_DELAY=-1
    ## file mode
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          # allow Hibernate to create DB table if doesn't exist
          auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
 
# access local db by http://localhost:8080/h2-console/
